pipeline {
  agent any

  parameters {
      string(defaultValue: "PROD", description: "Which environment to deploy?", name: "deployEnv")
  }

  stages {
    stage("Demo"){
      steps {
        echo "string is set to : ${params.deployEnv}"
      }
    }
  }
}